import { useParams, Link } from "wouter";
import { useGetSessionSettlement, getGetSessionSettlementQueryKey } from "@workspace/api-client-react";
import { Layout } from "@/components/Layout";
import { useAdmin } from "@/hooks/useAdmin";
import { ChevronLeft, ArrowRight, Phone, Share2, Copy, Check } from "lucide-react";
import { motion } from "framer-motion";
import { useState } from "react";

function buildWhatsAppText(settlement: {
  totalPot: number;
  totalRake: number;
  transfers: Array<{ fromName: string; toName: string; amount: number }>;
  players: Array<{ firstName: string; lastName: string; netProfit: number }>;
}): string {
  const date = new Date().toLocaleDateString("he-IL");
  const lines: string[] = [
    `🃏 *CHINO POKER — סיכום משחק*`,
    `📅 ${date}`,
    ``,
    `💰 *סה"כ קופה:* ${settlement.totalPot.toFixed(0)} ₪`,
    `🏦 *ריק:* ${settlement.totalRake.toFixed(0)} ₪ (10% רווח נקי)`,
    ``,
    `📊 *תוצאות שחקנים:*`,
    ...settlement.players.map(p =>
      `${p.netProfit >= 0 ? "🟢" : "🔴"} ${p.firstName} ${p.lastName}: ${p.netProfit > 0 ? "+" : ""}${p.netProfit.toFixed(0)} ₪`
    ),
    ``,
    `💸 *העברות:*`,
    ...(settlement.transfers.length === 0
      ? ["✅ אין העברות — כולם בכיסם"]
      : settlement.transfers.map(t => `💳 ${t.fromName} → ${t.toName}: ${t.amount.toFixed(0)} ₪`)),
    ``,
    `_Generated by Chino Poker_`,
  ];
  return lines.join("\n");
}

export default function SettlementPage() {
  const params = useParams<{ sessionId: string }>();
  const sessionId = parseInt(params.sessionId || "0");
  const { adminMode } = useAdmin();
  const [copied, setCopied] = useState(false);

  const { data: settlement } = useGetSessionSettlement(sessionId, {
    query: { queryKey: getGetSessionSettlementQueryKey(sessionId), enabled: !!sessionId }
  });

  const handleShare = async () => {
    if (!settlement) return;
    const text = buildWhatsAppText(settlement);
    if (navigator.share) {
      try {
        await navigator.share({ text });
        return;
      } catch {}
    }
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  if (!settlement) {
    return (
      <Layout adminMode={adminMode}>
        <div className="flex items-center justify-center py-20 text-gray-400">Loading...</div>
      </Layout>
    );
  }

  return (
    <Layout adminMode={adminMode}>
      <div className="p-4 max-w-xl mx-auto space-y-5 pb-8">

        {/* Back */}
        <Link href="/history" className="flex items-center gap-1 text-gray-400 hover:text-gray-700 text-sm transition-colors">
          <ChevronLeft className="w-4 h-4" />
          History
        </Link>

        {/* Header */}
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
          className="flex items-start justify-between">
          <div>
            <h1 className="font-cinzel text-gray-900 text-xl font-bold tracking-widest">SETTLEMENT</h1>
            <div className="flex gap-4 mt-1.5 text-xs text-gray-400">
              <span>Pot: <span className="text-gray-900 font-bold">{settlement.totalPot.toFixed(0)} ₪</span></span>
              <span>Rake: <span className="text-gray-900 font-bold">{settlement.totalRake.toFixed(0)} ₪</span></span>
            </div>
          </div>
          <button
            onClick={handleShare}
            className={`flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-semibold transition-all ${
              copied
                ? "bg-green-50 border border-green-200 text-green-600"
                : "bg-gray-100 border border-gray-200 text-gray-600 hover:border-green-400 hover:text-green-600"
            }`}
            data-testid="button-share"
          >
            {copied ? <Check className="w-3.5 h-3.5" /> : <Share2 className="w-3.5 h-3.5" />}
            {copied ? "Copied!" : "Share"}
          </button>
        </motion.div>

        {/* Who pays whom */}
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
          <div className="text-xs font-bold text-gray-400 tracking-widest mb-2.5">WHO PAYS WHOM</div>
          {settlement.transfers.length === 0 ? (
            <div className="text-center py-5 text-gray-400 text-sm bg-gray-50 border border-gray-100 rounded-2xl">
              ✅ All square — no transfers needed
            </div>
          ) : (
            <div className="space-y-2">
              {settlement.transfers.map((t, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.04 + 0.1 }}
                  className="bg-white border border-gray-200 rounded-2xl p-4 shadow-sm"
                  data-testid={`transfer-${i}`}
                >
                  <div className="flex items-center gap-2">
                    <div className="flex-1 min-w-0">
                      <div className="text-red-600 font-bold text-sm truncate">{t.fromName}</div>
                      {t.fromPhone && (
                        <div className="flex items-center gap-1 text-gray-400 text-xs mt-0.5">
                          <Phone className="w-3 h-3" />{t.fromPhone}
                        </div>
                      )}
                    </div>
                    <div className="flex flex-col items-center flex-shrink-0 px-2">
                      <div className="text-gray-900 font-black text-base">{t.amount.toFixed(0)} ₪</div>
                      <ArrowRight className="w-4 h-4 text-gray-300 mt-0.5" />
                    </div>
                    <div className="flex-1 min-w-0 text-right">
                      <div className="text-green-600 font-bold text-sm truncate">{t.toName}</div>
                      {t.toPhone && (
                        <div className="flex items-center gap-1 text-gray-400 text-xs mt-0.5 justify-end">
                          <Phone className="w-3 h-3" />{t.toPhone}
                        </div>
                      )}
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          )}
        </motion.div>

        {/* Player results */}
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
          <div className="text-xs font-bold text-gray-400 tracking-widest mb-2.5">PLAYER RESULTS</div>
          <div className="space-y-2">
            {settlement.players
              .slice()
              .sort((a, b) => b.netProfit - a.netProfit)
              .map((player, i) => (
                <motion.div
                  key={player.playerId}
                  initial={{ opacity: 0, x: -8 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.04 + 0.2 }}
                  className="bg-white border border-gray-200 rounded-2xl p-4 shadow-sm"
                  data-testid={`result-player-${player.playerId}`}
                >
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="text-gray-900 font-semibold text-sm">{player.firstName} {player.lastName}</div>
                      {player.phone && (
                        <div className="flex items-center gap-1 text-gray-400 text-xs mt-0.5">
                          <Phone className="w-3 h-3" />{player.phone}
                        </div>
                      )}
                    </div>
                    <div className="text-right">
                      <div className={`font-black text-lg ${player.netProfit > 0 ? "text-green-600" : player.netProfit < 0 ? "text-red-600" : "text-gray-400"}`}>
                        {player.netProfit > 0 ? "+" : ""}{player.netProfit.toFixed(0)} ₪
                      </div>
                      {player.rake > 0 && (
                        <div className="text-[10px] text-gray-400">rake: {player.rake.toFixed(1)} ₪</div>
                      )}
                    </div>
                  </div>
                  <div className="mt-2 flex gap-3 text-xs text-gray-400 pt-2 border-t border-gray-50">
                    <span>Buyins: {player.totalBuyins.toFixed(0)} ₪</span>
                    <span>Final: {player.finalChips} chips</span>
                    <span>Gross: {player.profit > 0 ? "+" : ""}{player.profit.toFixed(0)} ₪</span>
                  </div>
                </motion.div>
              ))}
          </div>
        </motion.div>

        {/* Group rake summary */}
        <motion.div
          initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.4 }}
          className="bg-red-600 rounded-2xl p-5 text-center"
        >
          <div className="text-red-100 font-cinzel font-bold tracking-widest text-xs mb-1">GROUP RAKE THIS SESSION</div>
          <div className="text-white text-3xl font-black">{settlement.totalRake.toFixed(0)} ₪</div>
          <div className="text-red-200 text-xs mt-1">10% of net profits — added to group treasury</div>
        </motion.div>
      </div>
    </Layout>
  );
}
